### ISSUE TITLE
Consider mentioning that Turbo should be disabled for login links

### ISSUE THREAD

**Issue by shepmaster** [auth0/omniauth-auth0#130]
### Describe the problem you'd like to have solved

In an application using [Turbo](https://turbo.hotwire.dev) (and I assume its predecessor [Turbolinks](https://github.com/turbolinks/turbolinks)), form submissions will be transformed into XHR / fetch requests that trigger a CORS request. This is not valid for the login action. 

[Other users have experienced the same problem](https://community.auth0.com/t/received-cors-issue-trying-to-reproduce-quickstart-demo-in-rails/60143/5).

### Describe the ideal solution

Update the docs (and quick start guide?) to mention this. Specifically for Turbo, you can disable the behavior via:

```ruby
button_to 'Login', 'auth/auth0', method: :post, data: { turbo: 'false' }
#                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by davidpatrick** [comment]
Thanks @shepmaster for raising, we can add an example to https://github.com/auth0/omniauth-auth0#examples to cover using with Turbo. Happy to review a PR if you would like to submit one.

**Comment by davidpatrick** [comment]
Looked into this and Turbolinks was disabled by default on POST requests it https://github.com/turbolinks/turbolinks-classic/issues/352#issuecomment-37015963 https://www.rubydoc.info/gems/turbolinks/2.5.3

The successor of that library, Turbo, has decided not to take this approach. However seeing as Turbo, which is still in beta (according to their readme) is a much more intentional opt-in than the bundled with rails Turbolinks, it should be well documented and covered in the Turbo documentation.

**Comment by fredoliveira** [comment]
FYI, this is quite relevant these days and should probably be reconsidered. A new rails project, with default parameters, will include `turbo` by default. This means the examples from the Auth0 documentation won't work.

The solution can be one of two things:

- Disable turbo for this specific link, like mentioned in the original issue description
- Disable turbo globally, which means commenting out turbo in the application pack

The first is the one I'd recommend, if you folks do end up changing the documentation.
