### ISSUE TITLE
How do I logout a user from my client app once his auth0 session has expired?

### ISSUE THREAD

**Issue by shadydealer** [auth0/omniauth-auth0#137]
### Describe the problem you'd like to have solved

I've started using Auth0 for SSO with a Rails client app and I'm having issues with the fact that once any of my users' Auth0 sessions have expired there's no way for me to know that so I can also destroy their session in the client app.

### Describe the ideal solution

Once the user's Auth0 session expires, a POST request is sent from Auth0 to the client Rails app, securely, that a specific user's session has expired.

E.g. suppose that we could generate a secret API key on a client application, similar to the way keys are generated by Auth0 so that client application could be authorize, but it's the other way around- Auth0 would have to authenticate itself to the client application when sending a request and the client application has to verify that request in order for it to be handled.

## Alternatives and current work-arounds
N/A

### Additional information, if any
N/A

**Comment by stevehobbsdev** [comment]
Thanks for your patience here. We are currently looking at options that would support the scenario you mention but we're not quite there yet, and unfortunately I don't have a timeline to share. However, just know that this is something we're looking into.

Keep an eye out for announcements in the [Auth0 Changelog](https://auth0.com/changelog) later in the year. If I hear of anything further I will try and update you here too.

In the meantime, one thing you could try in order to find out if you have a session is to send the `prompt=none` parameter to the login call, which should fail if there is no session, and then put the user through an interactive login if not.

Hope that helps!

**Comment by aalejandromr** [comment]
@stevehobbsdev @shadydealer 

Curious to know if you guys have found a workaround for this specific use case.

Thanks

**Comment by shadydealer** [comment]
@aalejandromr Sorry, I am no longer working on the project on which I needed this feature, so I cannot say.
