### ISSUE TITLE
Intermittent CSRF Detected

### ISSUE THREAD

**Issue by robwise** [auth0/omniauth-auth0#88]
### Description

Most of our users are reporting no issues, but occasionally we are seeing users hit CSRF detected errors. We even had a developer hit one locally.

### Reproduction

One nuance of our setup is that the entire app is behind a login wall, so we have a concern that automatically redirects to auth0 login if the user is not already logged in.

That code looks like this:

```ruby
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :authenticate!
  end

  def authenticate!
    authenticated_user = User.includes(:roles).find_by(id: session[:user_id])
    if authenticated_user.nil?
      redirect_to "/auth/auth0"
    else
      Current.user = authenticated_user
    end
  end
```

The error looks like this in development:

<img width="1571" alt="Screen Shot 2019-11-13 at 9 53 13 AM" src="https://user-images.githubusercontent.com/6173488/68787858-88508880-05ff-11ea-95ce-6eb5b20a0cac.png">

Unfortunately, we're having a lot of trouble reproducing it. My colleagues have shown it to me when it's happened and I see it coming into Sentry (our error reporter), but they didn't seem to do anything differently.

The strange thing is that usually they insist they were already signed in on a previous session and logically shouldn't have even been needing to go through the auth0 flow. 

- Visit site
- Get prompted with login again (even though they weren't signed out)
- Submit credentials
- Receive CSRF detected error page (which we render for the omniauth failure callback)
- If they then just type in the URL of the app again, they're signed in and everything's working

### Environment

- **Version of this library used:** 4.9.0
- **Version of the platform or framework used, if applicable:** Rails 5.2.3
- **Other relevant versions (language, server software, OS, browser):** English, Heroku, Linux, Chrome
- **Other modules/plugins/libraries that might be involved:** `omniauth-auth0@2.2.0`. We do not have the `omniauth-rails_csrf_protection` because of our redirect strategy (redirects don't allow `POST`) but maybe this is the issue?

**Comment by joshcanhelp** [comment]
@robwise - Apologies for the delay here. That notice typically has to do with a missing `state` parameter. This all happens in the core OmniAuth library but a value is generated, stored in session, and sent to Auth0 in a URL parameter. Then, when the user hits the callback URL, the value that's returned from Auth0 is compared with the stored value. 

If looks like your `if authenticated_user.nil?` clause is send the user to the login link, which should do the storage and redirect automatically. I can't see in the URL in the screenshot you posted but is there a `state` URL parameter? You'll want to check what's in session as well, it's most likely missing there for some reason.

I'm going to close this out for now since this is more on the parent library but please reply back if this looks more like a problem with our strategy. Again, apologies for the delay.
